web:
  image: nginx:latest
  restart: always
  ports:
    - "9999:80"
  volumes:
    - ./app_code:/code
    - ./app_settings/nginx-site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
    build: ./app_settings
    restart: always
    volumes:
        - ./app_code:/code
    #command: >
    #    bash -c "composer install -d /code/sampleSymphony"

mysql:
  image: mysql:latest
  restart: always
  ports:
    - "9998:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - "9997:80"
  environment:
    - PMA_HOST=mysql
  links: 
    - mysql