web:
  image: nginx:latest
  ports:
    - "9090:80"
  volumes:
    - ./app_code:/code
    - ./app_settings/nginx-site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
    build: ./app_settings
    volumes:
        - ./app_code:/code

mysql:
  image: mysql:latest
  ports:
    - "9091:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "9092:80"
  environment:
    - PMA_HOST=mysql
  links: 
    - mysql